## Titanic 예제 실습

In [1]:
import pandas as pd

In [2]:
# read_csv() : csv 파일을 읽어오는 메서드
# train Data : 학습이 완료된 데이터
# test Data : 학습이 올바르게 완료된 것인지 확인하기 위한 데이터
df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### column별 의미
    - PassengerId : 각 승객에게 주어진 고유 ID 번호
    - Survived : 생존여부(0 = 사망, 1 = 생존)
                 -> Target Data(= 종속 변수)
    - Pclass : 티켓 클래스(1 = 1등석, 2 = 2등석, 3 = 3등석) 
    - Sex : 성별
    - Age : 나이
    - SibSp : 함께 탑승한 형제자매/배우자의 수
    - Parch : 함께 탑승한 부모님/아이들의 수
    - Ticket : 티켓 번호
    - Fare : 탑승 요금
    - Cabin : 수하물 번호 또는 객실 카테고리
    - Embarked : 선착장
                 (C = Cherboug, Q = Queenstown, S = Southampton)

In [3]:
# head() : 주어진 데이터의 상위 5개를 기본적으로 보여줌(숫자 입력 시 숫자만큼 데이터를 보여줌)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# tail() : 주어진 데이터의 하위 5개를 기본적으로 보여줌(숫자 입력 시 숫자만큼 데이터를 보여줌)
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [7]:
# describe() : 주어진 데이터의 통계적인 정보를 얻을 때
#              include = 'all'을 집어넣으면 비수치적인 정보도 함께 얻을 수 있음
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [8]:
# 등급과 생존의 상관관계
print(df['Survived'].corr(df['Pclass']))
# 나이와 생존의 상관관계
print(df['Survived'].corr(df['Age']))

print(df['Survived'].corr(df['Parch']))
print(df['Survived'].corr(df['SibSp']))
# 문자로 된 데이터는 학습에 바로 사용이 불가능

-0.3384810359610148
-0.07722109457217755
0.0816294070834836
-0.035322498885735576

In [9]:
# 숫자 column에 대해서만 상관관계 도출
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [10]:
df.select_dtypes(include='number').corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [11]:
df[['SibSp', 'Parch', 'Fare']].corr()

          SibSp     Parch      Fare
SibSp  1.000000  0.414838  0.159651
Parch  0.414838  1.000000  0.216225
Fare   0.159651  0.216225  1.000000

In [12]:
df.mean(numeric_only=True)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [13]:
df.std(numeric_only=True)

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [14]:
df.groupby('Survived').mean(numeric_only=True)

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [15]:
df.groupby(['Sex', 'Survived']).mean(numeric_only=True)

                 PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived
female 0          434.851852  2.851852  25.046875  1.209877  1.037037
       1          429.699571  1.918455  28.847716  0.515021  0.515021
male   0          449.121795  2.476496  31.618056  0.440171  0.207265
       1          475.724771  2.018349  27.276022  0.385321  0.357798

                      Fare
Sex    Survived
female 0         23.024385
       1         51.938573
male   0         21.960993
       1         40.821484

In [16]:
# axis : 축 방향이 행 방향인지 열 방향인지 결정 (0 = 행방향, 1 = 열방향)
df1 = df.rename({'Name' : '이름'}, axis=1)
df1.head(2)

,PassengerId,Survived,Pclass,이름,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [17]:
df2 = df.rename(columns={'Age' : '나이'})
df2.head(1)

,PassengerId,Survived,Pclass,Name,Sex,나이,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [18]:
# 하나의 데이터에 대해서만 변환이 가능
df3 = df.Sex.map(lambda x : 0 if x == 'female' else 1)
df3.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [19]:
def n_square(x):
    return x**2

In [20]:
df4_1 = df['Age'].map(n_square)
df4_1

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
        ...
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [21]:
def n_square(x,n):
    return x**n

In [22]:
df4 = df[['Age', 'SibSp', 'Fare']].apply(n_square, n=2)
df4

        Age  SibSp         Fare
0     484.0      1    52.562500
1    1444.0      1  5081.308859
2     676.0      0    62.805625
3    1225.0      1  2819.610000
4    1225.0      0    64.802500
..      ...    ...          ...
886   729.0      0   169.000000
887   361.0      0   900.000000
888     NaN      1   549.902500
889   676.0      0   900.000000
890  1024.0      0    60.062500

[891 rows x 3 columns]

## 객체 연산

In [23]:
data = [[1, 10, 100], [2, 20, 200], [3, 30, 300]]
col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3
row1     1    10   100
row2     2    20   200
row3     3    30   300

In [24]:
result = df.add(1)
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [25]:
result = df + 1
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [26]:
data2 = [[3], [4], [5]]
df2 = pd.DataFrame(data2, index=['row1', 'row2', 'row3'], columns=['col1'])
df2

      col1
row1     3
row2     4
row3     5

In [27]:
# add() : 덧셈
# sub() : 뺄셈
# mul() : 곱셈
# div() : 나눗셈
# mod() : 나머지 연산
result = df.add(df2)
result

      col1  col2  col3
row1     4   NaN   NaN
row2     6   NaN   NaN
row3     8   NaN   NaN

In [28]:
# fill_value(0) : 동일한 부분이 없는 경우에, 0으로 채워서 연산을 진행
result = df.add(df2, fill_value=0)
result

      col1  col2   col3
row1     4  10.0  100.0
row2     6  20.0  200.0
row3     8  30.0  300.0

In [29]:
col = ['col1', 'col2']
row = ['row1', 'row2']
data1 = [[1, 2], [3, 4]]
data2 = [[5, 6], [7, 8]]
df1 = pd.DataFrame(data=data1)
df2 = pd.DataFrame(data=data2)

In [30]:
df1

   0  1
0  1  2
1  3  4

In [31]:
df2

   0  1
0  5  6
1  7  8

In [32]:
# 행렬 곱
df3 = df1.dot(df2)
df3

    0   1
0  19  22
1  43  50

In [33]:
import numpy as np

In [34]:
col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
data = np.random.rand(3, 3)*100
df = pd.DataFrame(data, row, col)
df

           col1       col2       col3
row1  79.602970  60.534087  36.820875
row2  40.531307  77.063191  69.929757
row3  63.248145  97.840238  18.492917

In [35]:
# round() : 반올림
df.round(0)

      col1  col2  col3
row1  80.0  61.0  37.0
row2  41.0  77.0  70.0
row3  63.0  98.0  18.0

In [36]:
df.round(2)

       col1   col2   col3
row1  79.60  60.53  36.82
row2  40.53  77.06  69.93
row3  63.25  97.84  18.49

In [37]:
col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
data = [[1, 2, 3], [4, 5, 6], [7, np.nan, 9]]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3
row1     1   2.0     3
row2     4   5.0     6
row3     7   NaN     9

In [38]:
df.sum(axis=0)

col1    12.0
col2     7.0
col3    18.0
dtype: float64

In [39]:
df.sum(axis=1)

row1     6.0
row2    15.0
row3    16.0
dtype: float64

In [40]:
# skipna = False : None 데이터를 skip 하지 않고 연산
#                  None 데이터는 연산 시 None을 결과로 출력
df.sum(axis=0, skipna=False)

col1    12.0
col2     NaN
col3    18.0
dtype: float64

In [41]:
# prod() : 곱셈
df.prod(axis=1)

row1      6.0
row2    120.0
row3     63.0
dtype: float64

In [42]:
df.prod(axis=0, skipna=False)

col1     28.0
col2      NaN
col3    162.0
dtype: float64

In [43]:
# 전치 행렬
# (=df.T)
df.transpose()

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [44]:
df.T

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [45]:
idx = ['A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'E', 'E', 'E']
col = ['col1', 'col2', 'col3']
# 데이터를 15행 3열로 제작
data = np.random.randint(0,9,(15,3))
# reset_index() : 인덱스를 새로 부여
#                 -> 기존 인덱스가 데이터가 됨
df = pd.DataFrame(data, idx, col).reset_index() 
df

   index  col1  col2  col3
0      A     3     8     2
1      A     6     6     2
2      B     7     6     0
3      B     5     8     2
4      B     0     4     4
5      C     7     0     5
6      C     1     5     7
7      C     0     7     8
8      D     3     3     6
9      D     3     4     2
10     D     1     6     6
11     D     6     7     6
12     E     1     4     7
13     E     6     7     5
14     E     0     1     5

In [46]:
df.groupby('index').mean()

           col1  col2      col3
index
A      4.500000   7.0  2.000000
B      4.000000   6.0  2.000000
C      2.666667   4.0  6.666667
D      3.250000   5.0  5.000000
E      2.333333   4.0  5.666667

In [47]:
df.groupby('index').count()

       col1  col2  col3
index
A         2     2     2
B         3     3     3
C         3     3     3
D         4     4     4
E         3     3     3

In [48]:
df.groupby('index').agg(['sum', 'mean'])

      col1           col2      col3
       sum      mean  sum mean  sum      mean
index
A        9  4.500000   14  7.0    4  2.000000
B       12  4.000000   18  6.0    6  2.000000
C        8  2.666667   12  4.0   20  6.666667
D       13  3.250000   20  5.0   20  5.000000
E        7  2.333333   12  4.0   17  5.666667

In [49]:
period = pd.period_range(start='2022-01-13 00:00:00', end='2022-01-13 02:30:00', freq='30min')
data = {'col1':[1,2,3,4,5,6], 'col2':period}
idx = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6']
df = pd.DataFrame(data, idx)
df

      col1              col2
row1     1  2022-01-13 00:00
row2     2  2022-01-13 00:30
row3     3  2022-01-13 01:00
row4     4  2022-01-13 01:30
row5     5  2022-01-13 02:00
row6     6  2022-01-13 02:30

In [50]:
# rolling() : 기간을 주고 데이터를 구하는 것
#             ex) rolling(window=3).sum() : 3개의 데이터를 가지고 누적된 합을  구하는 것
df.rolling(window=3).sum(numeric_only=True)

      col1
row1   NaN
row2   NaN
row3   6.0
row4   9.0
row5  12.0
row6  15.0

In [51]:
# rolling(window=3).mean() : 3개의 데이터를 가지고 누적된 평균을  구하는 것
df.rolling(window=3).mean(numeric_only=True)

      col1
row1   NaN
row2   NaN
row3   2.0
row4   3.0
row5   4.0
row6   5.0

In [52]:
data = {
    '2015':[9904312, 3448737, 2890451, 2466052],
    '2010':[9631482, 3393191, 2632035, 2431774],
    '2005':[9762546, 3512547, 2517680, 2456016],
    '2000':[9853972, 3655437, 2466338, 2473990],
    '지역':['수도권', '경상권', '수도권', '경상권'],
    '2010-2015 증가율':[0.0283, 0.0163, 0.0982, 0.0141],
}

column_list = ['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율']
index_list = ['서울', '부산', '인천', '대구']
df = pd.DataFrame(data, index_list, column_list)
df

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [55]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [56]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='str')

In [57]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [58]:
df.T

도시                  서울       부산       인천       대구
특성
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [59]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [60]:
# 2차원 구조의 데이터를 인덱싱할 때는 열 인덱스 먼저 지정후 행 인덱스를 지정
df['서울']

KeyError: '서울'

In [61]:
df.지역

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [62]:
df[['2010', '2015']]

특성     2010     2015
도시
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [65]:
# 한 개의 column이지만 리스트 형식으로 만들어서 값을 슬라이싱하게 되면 DataFrame 형식으로 값을 반환
df[['지역']]

특성   지역
도시
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [66]:
print(type(df['지역']))
print(type(df[['지역']]))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [73]:
# np.arange() 와 range() 함수는 동일하게 동작
# 최대 3개의 값을 대입할 수 있음
# reshape() : np.arrange()의 결과값 구조를 변형시킬 때 사용
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [71]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int64

In [77]:
# 데이터 수정
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          283.0          -1.34
부산  경상권  3448737  3393191  3512547  3655437          163.0          -3.40
인천  수도권  2890451  2632035  2517680  2466338          982.0           4.54
대구  경상권  2466052  2431774  2456016  2473990          141.0          -0.99

In [78]:
# 데이터 삽입
df['2005-2010 증가율'] = ((df['2010'] - df['2005']) / df['2005'] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          283.0          -1.34
부산  경상권  3448737  3393191  3512547  3655437          163.0          -3.40
인천  수도권  2890451  2632035  2517680  2466338          982.0           4.54
대구  경상권  2466052  2431774  2456016  2473990          141.0          -0.99

In [80]:
# 데이터 삭제
# df.drop('2010-2015 증가율', axis=1)과 동일하게 수행
del df['2010-2015 증가율']
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [81]:
# drop() 함수의 경우 반환값이 존재하기 때문에 변수가 필수로 존재해야 함
df3 = df.drop('2005-2010 증가율', axis=1)
df3

특성   지역     2015     2010     2005     2000
도시
서울  수도권  9904312  9631482  9762546  9853972
부산  경상권  3448737  3393191  3512547  3655437
인천  수도권  2890451  2632035  2517680  2466338
대구  경상권  2466052  2431774  2456016  2473990

In [82]:
df3 = df.drop('서울', axis=0)
df3

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [84]:
# 라벨 인덱스를 통해 접근할 때는 열 인덱스, 행 인덱스 순으로 지정
df['2015']['서울']

np.int64(9904312)

In [86]:
# 행 인덱스는 위치 인덱스를 통해 접근 가능
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [91]:
# 슬라이싱의 경우 라벨 인덱싱과 위치 인덱싱 모두 사용 가능
df['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [90]:
df[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [92]:
df.iloc[[0, 2]]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [93]:
df.iloc[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [94]:
df.loc[['서울', '부산']]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [95]:
df.loc['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [96]:
df = pd.DataFrame({'A':[1,4,7], 'B':[2,5,8], 'C':[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [98]:
# DataFrame에 직접 접근할 때는 열, 행 순으로 접근
# iloc() 또는 loc() 함수로 데이터에 접근할 때는 행, 열 순으로 접근
df.iloc[0]

A    1
B    2
C    3
Name: 0, dtype: int64

In [99]:
# 위치 인덱스를 사용
df.iloc[[0, 2]]

   A  B  C
0  1  2  3
2  7  8  9

In [100]:
# 라벨 인덱스를 사용
print(df.loc[0])

A    1
B    2
C    3
Name: 0, dtype: int64

In [101]:
df.loc[:, 'A']

0    1
1    4
2    7
Name: A, dtype: int64

In [102]:
df.loc[:, 'A':'B']

   A  B
0  1  2
1  4  5
2  7  8

In [103]:
df['A']

0    1
1    4
2    7
Name: A, dtype: int64

In [105]:
# 없는 열 이름을 불렀으므로 KeyError 발생
df[0]

KeyError: 0

In [106]:
df.loc[0]['B']

np.int64(2)

In [107]:
df['B'][0]

np.int64(2)