## 데이터 분석 제 1차 프로젝트

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 한글 깨짐 방지
plt.rcParams['font.family'] = 'Malgun Gothic'
# 마이너스 부호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 데이터 불러오기
df = pd.read_csv('./project1/pohang_train_2018_2023.csv')
df

,일시,지점,지점명,강수량(mm),강수량 QC플래그,source_file,date,daily_rain,water_level,heavy_rain
0,2018-01-01 00:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
1,2018-01-01 01:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
2,2018-01-01 02:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
3,2018-01-01 03:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
4,2018-01-01 04:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
...,...,...,...,...,...,...,...,...,...,...
52579,2023-12-31 19:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52580,2023-12-31 20:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52581,2023-12-31 21:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52582,2023-12-31 22:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52583,2023-12-31 23:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0

### column 별 의미
- datetime : 강수량 측정 날짜 및 시간
- hourly_rain : 시간별 강수량
- daily_rain : 일별 강수량
- water_level : 형산강의 일별 수위
- heavy_rain : 호우여부(호우 = 1, 호우X = 0, 호우 경보의 유무로 기준)

In [3]:
# 한글로 되어있는 인덱스 영어로 바꾸기
df1 = df.rename(columns = {
    '일시' : 'datetime',
    '강수량(mm)' : 'hourly_rain'})
df1

,datetime,지점,지점명,hourly_rain,강수량 QC플래그,source_file,date,daily_rain,water_level,heavy_rain
0,2018-01-01 00:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
1,2018-01-01 01:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
2,2018-01-01 02:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
3,2018-01-01 03:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
4,2018-01-01 04:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0
...,...,...,...,...,...,...,...,...,...,...
52579,2023-12-31 19:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52580,2023-12-31 20:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52581,2023-12-31 21:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52582,2023-12-31 22:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0
52583,2023-12-31 23:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0

In [4]:
# 'datetime'을 연'year'/월'month'/일'day'/시'time'로 구분해서 새로운 clumn 만들기
df1['datetime'] = pd.to_datetime(df1['datetime'])
df1['year'] = df1['datetime'].dt.year
df1['month'] = df1['datetime'].dt.month
df1['day'] = df1['datetime'].dt.day
df1['hour'] = df1['datetime'].dt.hour
df1

,datetime,지점,지점명,hourly_rain,강수량 QC플래그,source_file,date,daily_rain,water_level,heavy_rain,year,month,day,hour
0,2018-01-01 00:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0,2018,1,1,0
1,2018-01-01 01:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0,2018,1,1,1
2,2018-01-01 02:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0,2018,1,1,2
3,2018-01-01 03:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0,2018,1,1,3
4,2018-01-01 04:00:00,138,포항,0.0,NaN,NaN,2018-01-01,0.0,0.97,0,2018,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52579,2023-12-31 19:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0,2023,12,31,19
52580,2023-12-31 20:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0,2023,12,31,20
52581,2023-12-31 21:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0,2023,12,31,21
52582,2023-12-31 22:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0,2023,12,31,22
52583,2023-12-31 23:00:00,138,포항,0.0,9.0,포항_시간강수량_2023.csv,2023-12-31,0.0,1.16,0,2023,12,31,23

In [5]:
# 필요한 column들만 모으기
df1 = df[['year', 'month', 'day', 'hour', 'hourly_rain', 'daily_rain', 'water_level', 'heavy_rain']]
df1

KeyError: "['year', 'month', 'day', 'hour', 'hourly_rain'] not in index"

### 누적 강수량 Feature 만들기

In [ ]:
# 3시간 누적 강수량
df1['rain_3h'] = df1['hourly_rain'].rolling(3).sum()
# 6시간 누적 강수량
df1['rain_6h'] = df1['hourly_rain'].rolling(6).sum()
# 9시간 누적 강수량
df1['rain_9h'] = df1['hourly_rain'].rolling(9).sum()
# 12시간 누적 강수량
df1['rain_12h'] = df1['hourly_rain'].rolling(12).sum()
# Nan 데이터 0으로 채우기
df1 = df1.fillna(0)
df1