## Titanic 예제 실습

In [1]:
import pandas as pd

In [2]:
# read_csv() : csv 파일을 읽어오는 메서드
# train Data : 학습이 완료된 데이터
# test Data : 학습이 올바르게 완료된 것인지 확인하기 위한 데이터
df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### column별 의미
    - PassengerId : 각 승객에게 주어진 고유 ID 번호
    - Survived : 생존여부(0 = 사망, 1 = 생존)
                 -> Target Data(= 종속 변수)
    - Pclass : 티켓 클래스(1 = 1등석, 2 = 2등석, 3 = 3등석) 
    - Sex : 성별
    - Age : 나이
    - SibSp : 함께 탑승한 형제자매/배우자의 수
    - Parch : 함께 탑승한 부모님/아이들의 수
    - Ticket : 티켓 번호
    - Fare : 탑승 요금
    - Cabin : 수하물 번호 또는 객실 카테고리
    - Embarked : 선착장
                 (C = Cherboug, Q = Queenstown, S = Southampton)

In [3]:
# head() : 주어진 데이터의 상위 5개를 기본적으로 보여줌(숫자 입력 시 숫자만큼 데이터를 보여줌)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# tail() : 주어진 데이터의 하위 5개를 기본적으로 보여줌(숫자 입력 시 숫자만큼 데이터를 보여줌)
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [7]:
# describe() : 주어진 데이터의 통계적인 정보를 얻을 때
#              include = 'all'을 집어넣으면 비수치적인 정보도 함께 얻을 수 있음
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [8]:
# 등급과 생존의 상관관계
print(df['Survived'].corr(df['Pclass']))
# 나이와 생존의 상관관계
print(df['Survived'].corr(df['Age']))

print(df['Survived'].corr(df['Parch']))
print(df['Survived'].corr(df['SibSp']))
# 문자로 된 데이터는 학습에 바로 사용이 불가능

-0.3384810359610148
-0.07722109457217755
0.0816294070834836
-0.035322498885735576

In [9]:
# 숫자 column에 대해서만 상관관계 도출
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [10]:
df.select_dtypes(include='number').corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [11]:
df[['SibSp', 'Parch', 'Fare']].corr()

          SibSp     Parch      Fare
SibSp  1.000000  0.414838  0.159651
Parch  0.414838  1.000000  0.216225
Fare   0.159651  0.216225  1.000000

In [12]:
df.mean(numeric_only=True)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [13]:
df.std(numeric_only=True)

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [14]:
df.groupby('Survived').mean(numeric_only=True)

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [15]:
df.groupby(['Sex', 'Survived']).mean(numeric_only=True)

                 PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived
female 0          434.851852  2.851852  25.046875  1.209877  1.037037
       1          429.699571  1.918455  28.847716  0.515021  0.515021
male   0          449.121795  2.476496  31.618056  0.440171  0.207265
       1          475.724771  2.018349  27.276022  0.385321  0.357798

                      Fare
Sex    Survived
female 0         23.024385
       1         51.938573
male   0         21.960993
       1         40.821484

In [16]:
# axis : 축 방향이 행 방향인지 열 방향인지 결정 (0 = 행방향, 1 = 열방향)
df1 = df.rename({'Name' : '이름'}, axis=1)
df1.head(2)

,PassengerId,Survived,Pclass,이름,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [17]:
df2 = df.rename(columns={'Age' : '나이'})
df2.head(1)

,PassengerId,Survived,Pclass,Name,Sex,나이,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [18]:
# 하나의 데이터에 대해서만 변환이 가능
df3 = df.Sex.map(lambda x : 0 if x == 'female' else 1)
df3.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [19]:
def n_square(x):
    return x**2

In [20]:
df4_1 = df['Age'].map(n_square)
df4_1

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
        ...
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [21]:
def n_square(x,n):
    return x**n

In [22]:
df4 = df[['Age', 'SibSp', 'Fare']].apply(n_square, n=2)
df4

        Age  SibSp         Fare
0     484.0      1    52.562500
1    1444.0      1  5081.308859
2     676.0      0    62.805625
3    1225.0      1  2819.610000
4    1225.0      0    64.802500
..      ...    ...          ...
886   729.0      0   169.000000
887   361.0      0   900.000000
888     NaN      1   549.902500
889   676.0      0   900.000000
890  1024.0      0    60.062500

[891 rows x 3 columns]

## 객체 연산

In [23]:
data = [[1, 10, 100], [2, 20, 200], [3, 30, 300]]
col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3
row1     1    10   100
row2     2    20   200
row3     3    30   300

In [24]:
result = df.add(1)
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [25]:
result = df + 1
result

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [26]:
data2 = [[3], [4], [5]]
df2 = pd.DataFrame(data2, index=['row1', 'row2', 'row3'], columns=['col1'])
df2

      col1
row1     3
row2     4
row3     5

In [27]:
# add() : 덧셈
# sub() : 뺄셈
# mul() : 곱셈
# div() : 나눗셈
# mod() : 나머지 연산
result = df.add(df2)
result

      col1  col2  col3
row1     4   NaN   NaN
row2     6   NaN   NaN
row3     8   NaN   NaN

In [28]:
# fill_value(0) : 동일한 부분이 없는 경우에, 0으로 채워서 연산을 진행
result = df.add(df2, fill_value=0)
result

      col1  col2   col3
row1     4  10.0  100.0
row2     6  20.0  200.0
row3     8  30.0  300.0

In [29]:
col = ['col1', 'col2']
row = ['row1', 'row2']
data1 = [[1, 2], [3, 4]]
data2 = [[5, 6], [7, 8]]
df1 = pd.DataFrame(data=data1)
df2 = pd.DataFrame(data=data2)

In [30]:
df1

   0  1
0  1  2
1  3  4

In [31]:
df2

   0  1
0  5  6
1  7  8

In [32]:
# 행렬 곱
df3 = df1.dot(df2)
df3

    0   1
0  19  22
1  43  50

In [33]:
import numpy as np

In [34]:
col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
data = np.random.rand(3, 3)*100
df = pd.DataFrame(data, row, col)
df

           col1       col2       col3
row1  24.656400  77.282700   1.700077
row2  45.723387  70.174118  40.019601
row3  98.030221  69.968301  36.853188

In [35]:
# round() : 반올림
df.round(0)

      col1  col2  col3
row1  25.0  77.0   2.0
row2  46.0  70.0  40.0
row3  98.0  70.0  37.0

In [36]:
df.round(2)

       col1   col2   col3
row1  24.66  77.28   1.70
row2  45.72  70.17  40.02
row3  98.03  69.97  36.85

In [37]:
col = ['col1', 'col2', 'col3']
row = ['row1', 'row2', 'row3']
data = [[1, 2, 3], [4, 5, 6], [7, np.nan, 9]]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3
row1     1   2.0     3
row2     4   5.0     6
row3     7   NaN     9

In [38]:
df.sum(axis=0)

col1    12.0
col2     7.0
col3    18.0
dtype: float64

In [39]:
df.sum(axis=1)

row1     6.0
row2    15.0
row3    16.0
dtype: float64

In [40]:
# skipna = False : None 데이터를 skip 하지 않고 연산
#                  None 데이터는 연산 시 None을 결과로 출력
df.sum(axis=0, skipna=False)

col1    12.0
col2     NaN
col3    18.0
dtype: float64

In [41]:
# prod() : 곱셈
df.prod(axis=1)

row1      6.0
row2    120.0
row3     63.0
dtype: float64

In [42]:
df.prod(axis=0, skipna=False)

col1     28.0
col2      NaN
col3    162.0
dtype: float64

In [43]:
# 전치 행렬
# (=df.T)
df.transpose()

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [44]:
df.T

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [45]:
idx = ['A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'E', 'E', 'E']
col = ['col1', 'col2', 'col3']
# 데이터를 15행 3열로 제작
data = np.random.randint(0,9,(15,3))
# reset_index() : 인덱스를 새로 부여
#                 -> 기존 인덱스가 데이터가 됨
df = pd.DataFrame(data, idx, col).reset_index() 
df

   index  col1  col2  col3
0      A     1     1     8
1      A     5     1     2
2      B     5     0     4
3      B     8     6     8
4      B     6     0     6
5      C     5     1     0
6      C     3     1     5
7      C     6     7     4
8      D     4     0     7
9      D     5     2     1
10     D     8     0     6
11     D     1     0     0
12     E     3     3     3
13     E     3     8     4
14     E     7     1     4

In [46]:
df.groupby('index').mean()

           col1  col2      col3
index
A      3.000000   1.0  5.000000
B      6.333333   2.0  6.000000
C      4.666667   3.0  3.000000
D      4.500000   0.5  3.500000
E      4.333333   4.0  3.666667

In [47]:
df.groupby('index').count()

       col1  col2  col3
index
A         2     2     2
B         3     3     3
C         3     3     3
D         4     4     4
E         3     3     3

In [48]:
df.groupby('index').agg(['sum', 'mean'])

      col1           col2      col3
       sum      mean  sum mean  sum      mean
index
A        6  3.000000    2  1.0   10  5.000000
B       19  6.333333    6  2.0   18  6.000000
C       14  4.666667    9  3.0    9  3.000000
D       18  4.500000    2  0.5   14  3.500000
E       13  4.333333   12  4.0   11  3.666667

In [49]:
period = pd.period_range(start='2022-01-13 00:00:00', end='2022-01-13 02:30:00', freq='30min')
data = {'col1':[1,2,3,4,5,6], 'col2':period}
idx = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6']
df = pd.DataFrame(data, idx)
df

      col1              col2
row1     1  2022-01-13 00:00
row2     2  2022-01-13 00:30
row3     3  2022-01-13 01:00
row4     4  2022-01-13 01:30
row5     5  2022-01-13 02:00
row6     6  2022-01-13 02:30

In [50]:
# rolling() : 기간을 주고 데이터를 구하는 것
#             ex) rolling(window=3).sum() : 3개의 데이터를 가지고 누적된 합을  구하는 것
df.rolling(window=3).sum(numeric_only=True)

      col1
row1   NaN
row2   NaN
row3   6.0
row4   9.0
row5  12.0
row6  15.0

In [51]:
# rolling(window=3).mean() : 3개의 데이터를 가지고 누적된 평균을  구하는 것
df.rolling(window=3).mean(numeric_only=True)

      col1
row1   NaN
row2   NaN
row3   2.0
row4   3.0
row5   4.0
row6   5.0

In [52]:
data = {
    '2015':[9904312, 3448737, 2890451, 2466052],
    '2010':[9631482, 3393191, 2632035, 2431774],
    '2005':[9762546, 3512547, 2517680, 2456016],
    '2000':[9853972, 3655437, 2466338, 2473990],
    '지역':['수도권', '경상권', '수도권', '경상권'],
    '2010-2015 증가율':[0.0283, 0.0163, 0.0982, 0.0141],
}

column_list = ['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율']
index_list = ['서울', '부산', '인천', '대구']
df = pd.DataFrame(data, index_list, column_list)
df

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [53]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [54]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='str')

In [55]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [56]:
df.T

도시                  서울       부산       인천       대구
특성
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [57]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [58]:
# 2차원 구조의 데이터를 인덱싱할 때는 열 인덱스 먼저 지정후 행 인덱스를 지정
df['서울']

KeyError: '서울'

In [59]:
df.지역

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [60]:
df[['2010', '2015']]

특성     2010     2015
도시
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [61]:
# 한 개의 column이지만 리스트 형식으로 만들어서 값을 슬라이싱하게 되면 DataFrame 형식으로 값을 반환
df[['지역']]

특성   지역
도시
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [62]:
print(type(df['지역']))
print(type(df[['지역']]))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [63]:
# np.arange() 와 range() 함수는 동일하게 동작
# 최대 3개의 값을 대입할 수 있음
# reshape() : np.arrange()의 결과값 구조를 변형시킬 때 사용
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [64]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int64

In [67]:
# 데이터 수정
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [68]:
# 데이터 삽입
df['2005-2010 증가율'] = ((df['2010'] - df['2005']) / df['2005'] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [69]:
# 데이터 삭제
# df.drop('2010-2015 증가율', axis=1)과 동일하게 수행
del df['2010-2015 증가율']
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [70]:
# drop() 함수의 경우 반환값이 존재하기 때문에 변수가 필수로 존재해야 함
df3 = df.drop('2005-2010 증가율', axis=1)
df3

특성   지역     2015     2010     2005     2000
도시
서울  수도권  9904312  9631482  9762546  9853972
부산  경상권  3448737  3393191  3512547  3655437
인천  수도권  2890451  2632035  2517680  2466338
대구  경상권  2466052  2431774  2456016  2473990

In [71]:
df3 = df.drop('서울', axis=0)
df3

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [72]:
# 라벨 인덱스를 통해 접근할 때는 열 인덱스, 행 인덱스 순으로 지정
df['2015']['서울']

np.int64(9904312)

In [73]:
# 행 인덱스는 위치 인덱스를 통해 접근 가능
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [74]:
# 슬라이싱의 경우 라벨 인덱싱과 위치 인덱싱 모두 사용 가능
df['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [75]:
df[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [76]:
df.iloc[[0, 2]]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [77]:
df.iloc[0:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [78]:
df.loc[['서울', '부산']]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [79]:
df.loc['서울':'부산']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [80]:
df = pd.DataFrame({'A':[1,4,7], 'B':[2,5,8], 'C':[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [81]:
# DataFrame에 직접 접근할 때는 열, 행 순으로 접근
# iloc() 또는 loc() 함수로 데이터에 접근할 때는 행, 열 순으로 접근
df.iloc[0]

A    1
B    2
C    3
Name: 0, dtype: int64

In [82]:
# 위치 인덱스를 사용
df.iloc[[0, 2]]

   A  B  C
0  1  2  3
2  7  8  9

In [83]:
# 라벨 인덱스를 사용
print(df.loc[0])

A    1
B    2
C    3
Name: 0, dtype: int64

In [84]:
df.loc[:, 'A']

0    1
1    4
2    7
Name: A, dtype: int64

In [85]:
df.loc[:, 'A':'B']

   A  B
0  1  2
1  4  5
2  7  8

In [86]:
df['A']

0    1
1    4
2    7
Name: A, dtype: int64

In [87]:
# 없는 열 이름을 불렀으므로 KeyError 발생
df[0]

KeyError: 0

In [88]:
df.loc[0]['B']

np.int64(2)

In [89]:
df['B'][0]

np.int64(2)

In [90]:
import pandas as pd
import numpy as np

In [91]:

data = {'col1':[1,4,7], 'col2':[2,5,8], 'col3':[3,6,9]}
idx = ['row1', 'row2', 'row3']
df = pd.DataFrame(data, idx)
df

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [92]:
result = df.loc['row1':'row3', 'col2']
result

row1    2
row2    5
row3    8
Name: col2, dtype: int64

In [93]:
bool2 = [False, True, False]
result = df.loc[bool2]
result

      col1  col2  col3
row2     4     5     6

In [94]:
# df에서 col3의 자료값이 5 이상인 행만 출력
result = df.loc[df['col3'] > 5]
result

      col1  col2  col3
row2     4     5     6
row3     7     8     9

In [95]:
# 첫째, df의 col3에서 자료값이 5이상인 행만 출력
# 둘째, 그 중 col2민 출력
result = df.loc[df['col3'] > 5, ['col2']]
result

      col2
row2     5
row3     8

In [96]:
result = df.loc[lambda df : df['col2'] == 5]
result

      col1  col2  col3
row2     4     5     6

In [97]:
df.loc[['row1', 'row3'], ['col3']] = 10
df

      col1  col2  col3
row1     1     2    10
row2     4     5     6
row3     7     8    10

In [98]:
# 타입 오류 발생
df.loc[:, ['col3']] = 'B'
df

TypeError: Invalid value 'B' for dtype 'int64'

In [130]:
index_tuples  = [('row1', 'val1'), ('row1', 'val2'), ('row2', 'val1'), ('row2', 'val2'),
                ('row2', 'val3'), ('row3', 'val2'), ('row3', 'val3'),]
values = [[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18], [19,20,21]]
# 인덱스 설정 : from_tuples -> tuple에서 index를 불러옴
#              MultiIndexs -> tuple에서 가져온 값들을 멀티인덱스로 만듦
index = pd.MultiIndex.from_tuples(index_tuples)   
df = pd.DataFrame(values, columns=['col1', 'col2', 'col3'], index=index)
df

           col1  col2  col3
row1 val1     1     2     3
     val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18
     val3    19    20    21

In [131]:
result = df.loc['row2']
result

      col1  col2  col3
val1     7     8     9
val2    10    11    12
val3    13    14    15

In [132]:
result = df.loc[('row2','val2')]
result

col1    10
col2    11
col3    12
Name: (row2, val2), dtype: int64

In [133]:
result = df.loc[[('row2','val2')]]
result

           col1  col2  col3
row2 val2    10    11    12

In [134]:
result = df.loc[('row2','val2'), 'col3']
result

np.int64(12)

In [135]:
result = df.loc[('row1','val2') : ('row3','val2')]
result

           col1  col2  col3
row1 val2     4     5     6
row2 val1     7     8     9
     val2    10    11    12
     val3    13    14    15
row3 val2    16    17    18

In [136]:
data = [
    [100, 900, 800, 700],
    [1200, 1400, 900, 800]
]
columns = [
    ['영업이익', '영업이익', '당기순이익', '당기순이익'],
    ['컨센서스', '잠정치', '컨센서스', '잠정치']
]
index = ['2020/06', '2020/09']
df = pd.DataFrame(data, index, columns)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [104]:
data = [
    [100, 900, 800, 700],
    [1200, 1400, 900, 800]
]
index = ['2020/06', '2020/09']
level_0 = ['영업이익', '당기순이익']
level_1 = ['컨센서스', '잠정치']
idx = pd.MultiIndex.from_product([level_0, level_1])
df = pd.DataFrame(data, index, idx)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [105]:
import io

csv = '''
	A팀		B팀		C팀	
	삼성전자	카카오	삼성전자	카카오	삼성전자	카카오
2023-08-14	10	20	30	40	50	60
2023-08-16	20	20	30	40	50	60
2023-08-17	30	40	10	20	50	60
2023-08-18	30	40	10	20	50	60
2023-08-21	30	40	30	40	30	40
'''
# io.StringIO() : 문자열 데이터를 파일처럼 사용
# index_col=0 : 0번째 열을 인덱스로 사용
# header=[0,1] : 0번째, 1번째 행을 헤더로 사용
df_csv = pd.read_csv(io.StringIO(csv), sep='\t', index_col=0, header=[0, 1])
df_csv

,A팀,Unnamed: 2_level_0,B팀,Unnamed: 4_level_0,C팀,Unnamed: 6_level_0
,삼성전자,카카오,삼성전자,카카오,삼성전자,카카오
2023-08-14,10,20,30,40,50,60
2023-08-16,20,20,30,40,50,60
2023-08-17,30,40,10,20,50,60
2023-08-18,30,40,10,20,50,60
2023-08-21,30,40,30,40,30,40

In [106]:
df1 = df_csv.columns.to_frame(index=False).apply(lambda x: x.mask(x.str.contains('Unnamed'))).ffill()
df_csv = df_csv.set_axis(pd.MultiIndex.from_frame(df1, names=[''] * len(df_csv.columns[0])), axis=1)
df_csv

             A팀       B팀       C팀
           삼성전자 카카오 삼성전자 카카오 삼성전자 카카오
2023-08-14   10  20   30  40   50  60
2023-08-16   20  20   30  40   50  60
2023-08-17   30  40   10  20   50  60
2023-08-18   30  40   10  20   50  60
2023-08-21   30  40   30  40   30  40

In [107]:
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [108]:
df['영업이익']

         컨센서스   잠정치
2020/06   100   900
2020/09  1200  1400

In [109]:
df[[('영업이익','컨센서스')]]

         영업이익
         컨센서스
2020/06   100
2020/09  1200

In [110]:
df.loc['2020/06', '영업이익']

컨센서스    100
잠정치     900
Name: 2020/06, dtype: int64

In [111]:
df.loc[['2020/06'], ['영업이익']]

        영업이익
        컨센서스  잠정치
2020/06  100  900

In [112]:
df.loc['2020/06', ('영업이익', '컨센서스')]

np.int64(100)

In [113]:
# slice(None) : [:] 슬라이스와 동일한 의미
#               멀티 인덱스의 특정 레벨 내의 모든 값
df.loc[['2020/06'], (slice(None), '컨센서스')]

        영업이익 당기순이익
        컨센서스  컨센서스
2020/06  100   800

In [114]:
df2 = df.T
df2

            2020/06  2020/09
영업이익  컨센서스      100     1200
      잠정치       900     1400
당기순이익 컨센서스      800      900
      잠정치       700      800

In [115]:
df2.loc[('영업이익', '컨센서스'), '2020/06']

np.int64(100)

In [116]:
df2.loc[[('영업이익', '컨센서스')], '2020/06']

영업이익  컨센서스    100
Name: 2020/06, dtype: int64

In [117]:
df2.loc[[('영업이익', '컨센서스')], ['2020/06']]

           2020/06
영업이익 컨센서스      100

In [118]:
df2.loc[(slice(None), '컨센서스'), :]

            2020/06  2020/09
영업이익  컨센서스      100     1200
당기순이익 컨센서스      800      900

In [119]:
col1 = [1, 2, 3, 4, 5]
col2 = ['one', 'two', 'three', 'four', 'five']
col3 = [1.5, 2.5, 3.5, 4.5, 5.5]
col4 = [True, False, False, True, True]
df = pd.DataFrame({'col1': col1, 'col2': col2, 'col3': col3, 'col4': col4})
df

   col1   col2  col3   col4
0     1    one   1.5   True
1     2    two   2.5  False
2     3  three   3.5  False
3     4   four   4.5   True
4     5   five   5.5   True

In [120]:
 df.dtypes

col1      int64
col2        str
col3    float64
col4       bool
dtype: object

In [121]:
result = df.select_dtypes(include=['float', 'bool'])
result

   col3   col4
0   1.5   True
1   2.5  False
2   3.5  False
3   4.5   True
4   5.5   True

In [122]:
result = df.select_dtypes(exclude=['int64'])
result

    col2  col3   col4
0    one   1.5   True
1    two   2.5  False
2  three   3.5  False
3   four   4.5   True
4   five   5.5   True

In [123]:
col = ['alpha', 'beta', 'gamma', 'delta', 'epsilon']
row = ['sigma', 'omega', 'lambda']
data = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]
df = pd.DataFrame(data,row,col)
df

        alpha  beta  gamma  delta  epsilon
sigma       1     2      3      4        5
omega       6     7      8      9       10
lambda     11    12     13     14       15

In [124]:
df.filter(items=['alpha','delta'])

        alpha  delta
sigma       1      4
omega       6      9
lambda     11     14

In [125]:
df.filter(items=['omega'],axis=0)

       alpha  beta  gamma  delta  epsilon
omega      6     7      8      9       10

In [126]:
# like='ta' : 'ta'가 포함된 라벨의 자료값을 모두 출력
df.filter(like='ta')

        beta  delta
sigma      2      4
omega      7      9
lambda    12     14

In [127]:
# regex='[]' : 정규표현식을 나타낼때 사용
# regex='[mn]' : m 또는 n이 포함된 모든 라벨의 값들을 출력
df.filter(regex='[mn]')

        gamma  epsilon
sigma       3        5
omega       8       10
lambda     13       15

In [128]:
# ^g : g로 시작하는 라벨의 값들을 모두 출력
df.filter(regex='^g')

        gamma
sigma       3
omega       8
lambda     13

In [129]:
# a$ : a로 끝나는 라벨의 값들을 모두 출력
df.filter(regex='a$')

        alpha  beta  gamma  delta
sigma       1     2      3      4
omega       6     7      8      9
lambda     11    12     13     14

In [139]:
import pandas as pd

df = pd.read_csv('./titanic/train.csv')
df.iloc[0:5, 1:4]

   Survived  Pclass                                               Name
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

In [140]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [141]:
df[['Name', 'Age', 'Sex', 'Survived']]

                                                  Name   Age     Sex  Survived
0                              Braund, Mr. Owen Harris  22.0    male         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female         1
2                               Heikkinen, Miss. Laina  26.0  female         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female         1
4                             Allen, Mr. William Henry  35.0    male         0
..                                                 ...   ...     ...       ...
886                              Montvila, Rev. Juozas  27.0    male         0
887                       Graham, Miss. Margaret Edith  19.0  female         1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female         0
889                              Behr, Mr. Karl Howell  26.0    male         1
890                                Dooley, Mr. Patrick  32.0    male         0

[891 rows x 4 columns]

In [142]:
mask = (df['Sex'] == 'female')
mask

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [145]:
df[df['Sex'] == 'female']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [146]:
df9 = df[df['PassengerId'] == 3]['Name']
df9

2    Heikkinen, Miss. Laina
Name: Name, dtype: str

In [147]:
df9.values

<StringArray>
['Heikkinen, Miss. Laina']
Length: 1, dtype: str

In [148]:
df['family'] = df['SibSp'] + df['Parch']
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1

### DataFrame에 인덱스 설정

In [153]:
df = pd.DataFrame({'A':[1,4,7], 'B':[2,5,8], 'C':[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [154]:
# set_index('A') : A열의 값을 인덱스로 사용
df =df.set_index('A')
df

   B  C
A
1  2  3
4  5  6
7  8  9

### DataFrame에 행 추가

In [155]:
df = pd.DataFrame(data = np.array([[1,2,3], [4,5,6], [7,8,9]]),
                 columns=[48,49,50])
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9

In [156]:
a = pd.DataFrame(data=[[1,2,3]], columns=[48,49,50])
a

   48  49  50
0   1   2   3

In [160]:
df = pd.concat([df, a])
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
0   1   2   3

In [162]:
# drop=True : 새 인덱스 할당 시, 기존의 인덱스 유지 여부
#             (True = 유지X, False = 유지)
df2 = df.reset_index(drop=True)
df2

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
3   1   2   3

In [163]:
df3 = df.reset_index(drop=False)
df3

   index  48  49  50
0      0   1   2   3
1      1   4   5   6
2      2   7   8   9
3      0   1   2   3

### DataFrame에 인덱스, 컬럼, 데이터 삭제

In [177]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                 columns=['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [178]:
# inplace=True : 기존 데이터의 유지 여부
#                (True = 유지X -> 반환값 없음
#                 False = 유지)
df2 = df.drop('A', axis=1, inplace=False)
df2

   B  C
0  2  3
1  5  6
2  8  9

In [179]:
df.drop('A', axis=1, inplace=True)
df2

   B  C
0  2  3
1  5  6
2  8  9

In [180]:
# drop의 default 값은 False
df.drop('B', axis=1)
df

   B  C
0  2  3
1  5  6
2  8  9

In [181]:
df.drop(2, axis=0, inplace=True)
df

   B  C
0  2  3
1  5  6

In [182]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                 columns=['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [183]:
df2 = df.drop([0,2], axis=0, inplace=False)
df2

   A  B  C
1  4  5  6

In [184]:
df2 = df.drop(['A','C'], axis=1, inplace=False)
df2

   B
0  2
1  5
2  8

In [196]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9], [40,50,60], [23,35,37]]),
                 index=[2.5, 12.6, 4.8, 4.8, 2.5],
                 columns=[48, 49, 50])
df

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8   40  50  60
2.5   23  35  37

In [197]:
df = df.reset_index()
df

   index  48  49  50
0    2.5   1   2   3
1   12.6   4   5   6
2    4.8   7   8   9
3    4.8  40  50  60
4    2.5  23  35  37

In [198]:
df1 = df.drop_duplicates(subset='index', keep='last').set_index('index')
df1

       48  49  50
index
12.6    4   5   6
4.8    40  50  60
2.5    23  35  37

In [199]:
df2 = df.drop_duplicates(subset='index', keep='first').set_index('index')
df2

       48  49  50
index
2.5     1   2   3
12.6    4   5   6
4.8     7   8   9

In [200]:
df3 = df.drop_duplicates(subset='index', keep=False).set_index('index')
df3

       48  49  50
index
12.6    4   5   6

In [201]:
df = pd.DataFrame(data=np.array([[1,2,3], [1,5,6], [7,8,9]]),
                 columns=['A', 'B', 'C'], index=[11, 22, 33])
df

    A  B  C
11  1  2  3
22  1  5  6
33  7  8  9

In [202]:
df.index[1]

np.int64(22)

In [203]:
df2 = df.drop(df.index[1])
df2

    A  B  C
11  1  2  3
33  7  8  9

In [205]:
df2 = df.drop(df.index[1], axis=0)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [204]:
df2 = df.drop(22)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [206]:
col = ['col1', 'col2', 'col3', 'col4', 'col5']
row = ['row1', 'row2', 'row3', 'row4']
data = [[1,2,3,pd.NA,5], [6,pd.NA,8,pd.NA,10], [11,12,13,14,15], [pd.NA,pd.NA,pd.NA,pd.NA,pd.NA,]]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3  col4  col5
row1     1     2     3  <NA>     5
row2     6  <NA>     8  <NA>    10
row3    11    12    13    14    15
row4  <NA>  <NA>  <NA>  <NA>  <NA>

In [208]:
# dropna() : 결측치를 모두 삭제
df2 = df.dropna(axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [210]:
df2 = df.dropna(axis=1)
df2

Empty DataFrame
Columns: []
Index: [row1, row2, row3, row4]

In [209]:
df2 = df.dropna(how='any', axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [211]:
col = ['col1', 'col2', 'col3', 'col4', 'col5']
row = ['row1', 'row2', 'row3', 'row4']
data = [[1,2,3,pd.NA,5], [6,pd.NA,8,pd.NA,10], [11,12,13,14,15], [pd.NA,pd.NA,pd.NA,pd.NA,pd.NA,]]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3  col4  col5
row1     1     2     3  <NA>     5
row2     6  <NA>     8  <NA>    10
row3    11    12    13    14    15
row4  <NA>  <NA>  <NA>  <NA>  <NA>

In [217]:
# 해당 축에 None을 제외한 자료값이 thresh 이상 존재해야 함
df2 = df.dropna(thresh=3)
df2

     col1  col2 col3  col4 col5
row1    1     2    3  <NA>    5
row2    6  <NA>    8  <NA>   10
row3   11    12   13    14   15

In [215]:
df2 = df.dropna(thresh=4)
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [218]:
# None이 존재하는지 'col1'과 'col2'에서만 확인
df2 = df.dropna(subset=['col1', 'col2'])
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [219]:
df.dropna(subset=['col1', 'col2'], inplace=True)
df

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [221]:
col = ['col1', 'col2', 'col3', 'col4', 'col5']
row = ['row1', 'row2', 'row3', 'row4', 'row5']
na = np.nan
data = [[na,2,na,4,na],
        [6,7,na,9,na],
        [11,na,na,14,15],
        [na,17,na,na,20],
        [na,22,na,na,25]]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3  col4  col5
row1   NaN   2.0   NaN   4.0   NaN
row2   6.0   7.0   NaN   9.0   NaN
row3  11.0   NaN   NaN  14.0  15.0
row4   NaN  17.0   NaN   NaN  20.0
row5   NaN  22.0   NaN   NaN  25.0

In [222]:
df2 = df.fillna('A')
df2

      col1  col2 col3  col4  col5
row1     A   2.0    A   4.0     A
row2   6.0   7.0    A   9.0     A
row3  11.0     A    A  14.0  15.0
row4     A  17.0    A     A  20.0
row5     A  22.0    A     A  25.0

In [223]:
dict = {'col1':'A','col2':'B','col3':'C','col4':'D','col5':'E',}
df.fillna(value=dict)

      col1  col2 col3  col4  col5
row1     A   2.0    C   4.0     E
row2   6.0   7.0    C   9.0     E
row3  11.0     B    C  14.0  15.0
row4     A  17.0    C     D  20.0
row5     A  22.0    C     D  25.0

In [225]:
df[['col1']].fillna(100)

       col1
row1  100.0
row2    6.0
row3   11.0
row4  100.0
row5  100.0

### merge()

In [226]:
df1 = pd.DataFrame({'고객번호':[1001, 1002, 1003, 1004, 1005, 1006, 1007],
                   '이름':['둘리', '도우너', '또치', '길동', '희동', '마이콜', '영희']},
                  columns=['고객번호', '이름'])
df1

   고객번호   이름
0  1001   둘리
1  1002  도우너
2  1003   또치
3  1004   길동
4  1005   희동
5  1006  마이콜
6  1007   영희

In [228]:
df2 = pd.DataFrame({'고객번호':[1001, 1001, 1005, 1006, 1008, 1001],
                   '금액':[10000, 20000, 15000, 5000, 100000, 30000]},
                  columns=['고객번호', '금액'])
df2

   고객번호      금액
0  1001   10000
1  1001   20000
2  1005   15000
3  1006    5000
4  1008  100000
5  1001   30000

In [230]:
# 기준 column을 따로 정하지않으면 공통 column으로 병합을 진행
df3 = pd.merge(df1, df2)
df3

   고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

In [231]:
df4 = pd.merge(df1, df2, how='outer')
df4

   고객번호   이름        금액
0  1001   둘리   10000.0
1  1001   둘리   20000.0
2  1001   둘리   30000.0
3  1002  도우너       NaN
4  1003   또치       NaN
5  1004   길동       NaN
6  1005   희동   15000.0
7  1006  마이콜    5000.0
8  1007   영희       NaN
9  1008  NaN  100000.0

In [232]:
# 왼쪽(df1)에 위치한 항목은 중복되더라도 추가
df5 = pd.merge(df1, df2, how='left')
df5

   고객번호   이름       금액
0  1001   둘리  10000.0
1  1001   둘리  20000.0
2  1001   둘리  30000.0
3  1002  도우너      NaN
4  1003   또치      NaN
5  1004   길동      NaN
6  1005   희동  15000.0
7  1006  마이콜   5000.0
8  1007   영희      NaN

In [234]:
# 오른쪽(df2)에 위치한 항목은 중복되더라도 추가
df6 = pd.merge(df1, df2, how='right')
df6

   고객번호   이름      금액
0  1001   둘리   10000
1  1001   둘리   20000
2  1005   희동   15000
3  1006  마이콜    5000
4  1008  NaN  100000
5  1001   둘리   30000

In [239]:
df1 = pd.DataFrame({
    '품종':['setosa', 'setosa', 'virginica', 'virginica'],
    '꽃잎길이':[1.4, 1.3, 1.5, 1.3]},
     columns=['품종', '꽃잎길이'])
df1

          품종  꽃잎길이
0     setosa   1.4
1     setosa   1.3
2  virginica   1.5
3  virginica   1.3

In [242]:
df2 = pd.DataFrame({
    '품종':['setosa', 'virginica', 'virginica','versicolor'],
    '꽃잎너비':[0.4, 0.3, 0.5, 0.3]},
     columns=['품종', '꽃잎너비'])
df2

           품종  꽃잎너비
0      setosa   0.4
1   virginica   0.3
2   virginica   0.5
3  versicolor   0.3

In [243]:
df3 = pd.merge(df1, df2)
df3

          품종  꽃잎길이  꽃잎너비
0     setosa   1.4   0.4
1     setosa   1.3   0.4
2  virginica   1.5   0.3
3  virginica   1.5   0.5
4  virginica   1.3   0.3
5  virginica   1.3   0.5

In [245]:
df1 = pd.DataFrame({
    '고객명': ['춘향', '춘향' ,'몽룡'],
    '날짜': ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터': ['20000', '30000', '100000']})
df1

  고객명          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [246]:
df2 = pd.DataFrame({
    '고객명': ['춘향', '몽룡'],
    '데이터': ['여자', '남자']})
df2

  고객명 데이터
0  춘향  여자
1  몽룡  남자

In [247]:
df3 = pd.merge(df1, df2, on='고객명')
df3

  고객명          날짜   데이터_x 데이터_y
0  춘향  2018-01-01   20000    여자
1  춘향  2018-01-02   30000    여자
2  몽룡  2018-01-01  100000    남자

In [248]:
df1 = pd.DataFrame({
    '이름': ['춘향', '춘향' ,'몽룡'],
    '날짜': ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터': ['20000', '30000', '100000']})
df1

   이름          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [249]:
df2 = pd.DataFrame({
    '성명': ['춘향', '몽룡'],
    '데이터': ['여자', '남자']})
df2

   성명 데이터
0  춘향  여자
1  몽룡  남자

In [250]:
df3 = pd.merge(df1, df2, left_on='이름', right_on='성명')
df3

   이름          날짜   데이터_x  성명 데이터_y
0  춘향  2018-01-01   20000  춘향    여자
1  춘향  2018-01-02   30000  춘향    여자
2  몽룡  2018-01-01  100000  몽룡    남자

In [255]:
df1 = pd.DataFrame({'도시': ['서울', '서울', '서울', '부산', '부산'],
                   '연도': [2000, 2005, 2010, 2000, 2005],
                   '인구': [9853972, 9762546, 9631482, 3655437, 3512547]})
df1

   도시    연도       인구
0  서울  2000  9853972
1  서울  2005  9762546
2  서울  2010  9631482
3  부산  2000  3655437
4  부산  2005  3512547

In [252]:
df2 = pd.DataFrame(np.arange(12).reshape((6, 2)),
                  index=[['부산', '부산', '서울', '서울', '서울', '서울'],
                        [2000, 2005, 2000, 2005, 2010, 2015]],
                  columns=['데이터1', '데이터2'])
df2

         데이터1  데이터2
부산 2000     0     1
   2005     2     3
서울 2000     4     5
   2005     6     7
   2010     8     9
   2015    10    11

In [256]:
df3 = pd.merge(df1, df2, left_on=['도시', '연도'], right_index=True)
df3

   도시    연도       인구  데이터1  데이터2
0  서울  2000  9853972     4     5
1  서울  2005  9762546     6     7
2  서울  2010  9631482     8     9
3  부산  2000  3655437     0     1
4  부산  2005  3512547     2     3

In [259]:
df1 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                  index=['a', 'c', 'e'],
                  columns=['서울', '부산'])
df1

    서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [260]:
df2 = pd.DataFrame([[7., 8.], [9., 10.], [11.,12.], [13., 14.]],
                  index=['b', 'c', 'd', 'e'],
                  columns=['대구', '광주'])
df2

     대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [261]:
df3 = pd.merge(df1, df2, how='outer', left_index=True, right_index=True)
df3

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [262]:
df3 = pd.merge(df1, df2, left_index=True, right_index=True)
df3

    서울   부산    대구    광주
c  3.0  4.0   9.0  10.0
e  5.0  6.0  13.0  14.0