In [1]:
import pandas as pd
import numpy as np
import io

### [문제1]

In [2]:
data = [['037730', '3R', 1510, 7.36],
       ['036360', '3SOFT', 1790, 1.65],
       ['005760', 'ACTS', 1185, 1.28]]
columns = ['종목코드', '종목명', '현재가', '등락률']
df = pd.DataFrame(data=data, columns=columns)
df.set_index('종목코드', inplace=True)
df

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
005760   ACTS  1185  1.28

In [3]:
# (1)
df['등락률']['037730']

np.float64(7.36)

In [4]:
# (2)
df.iloc[0:2]

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

In [5]:
# (3)
df.loc['037730':'036360']

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

In [6]:
# (4)
df.iloc[:, [0]]

          종목명
종목코드
037730     3R
036360  3SOFT
005760   ACTS

In [7]:
# (5)
df.iloc[[0], [0, 1]]

       종목명   현재가
종목코드
037730  3R  1510

In [8]:
# (6)
df[df['현재가'] >= 1500]

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

In [9]:
# (7)
x = df['현재가'] >= 1500 
y = df['현재가'] < 1700
df[x & y]

       종목명   현재가   등락률
종목코드
037730  3R  1510  7.36

### [문제2]

In [10]:
data = [['2차전지(생산)', 'SK이노베이션', 10.19, 1.29],
       ['해운', '팬오션', 21.23, 0.95], 
       ['시스템반도체', '티엘아이', 35.97, 1.12],
       ['해운', 'HMM', 21.52, 3.20],
       ['시스템반도체', '아이에이', 37.32, 3.55],
       ['2차전지(생산)', 'LG화학', 83.06, 3.75]]
columns = ['테마', '종목명', 'PER', 'PBR']
df = pd.DataFrame(data=data, columns=columns)
df

         테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
1        해운      팬오션  21.23  0.95
2    시스템반도체     티엘아이  35.97  1.12
3        해운      HMM  21.52  3.20
4    시스템반도체     아이에이  37.32  3.55
5  2차전지(생산)     LG화학  83.06  3.75

In [11]:
# (1)
df.groupby('테마')[['PER', 'PBR']].mean()

             PER    PBR
테마
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.375  2.075

In [12]:
# (2)
df.groupby('테마')[['종목명']].count()

          종목명
테마
2차전지(생산)    2
시스템반도체      2
해운          2

In [13]:
# (3)
df.groupby('테마')[['PER']].mean()

             PER
테마
2차전지(생산)  46.625
시스템반도체    36.645
해운        21.375

In [14]:
# (4)
df.groupby('테마')[['PER', 'PBR']].mean()

             PER    PBR
테마
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.375  2.075

In [15]:
# (5)
df.groupby('테마')[['PER']].min()

            PER
테마
2차전지(생산)  10.19
시스템반도체    35.97
해운        21.23

In [16]:
df.groupby('테마')[['PBR']].max()

           PBR
테마
2차전지(생산)  3.75
시스템반도체    3.55
해운        3.20

In [17]:
df.groupby('테마')[['PER', 'PBR']].agg(['min', 'max'])

            PER          PBR
            min    max   min   max
테마
2차전지(생산)  10.19  83.06  1.29  3.75
시스템반도체    35.97  37.32  1.12  3.55
해운        21.23  21.52  0.95  3.20

### [문제3]

In [18]:
data1 = {
    'ID' : [100, 101, 102, 103],
    'Name' : ['Brayden', 'Clara', 'Ella', 'Oliver']
}
data2 = [
    [100, '삼성전자'],
    [100, 'LG전자'],
    [101, '카카오'],
    [101, 'NAVER'],
    [101, '현대차']
]
df1 = pd.DataFrame(data1)
df1.set_index('ID', inplace=True)
df2 = pd.DataFrame(data=data2, columns=['ID','종목명'])
df2.set_index('ID', inplace=True)

In [19]:
df1

        Name
ID
100  Brayden
101    Clara
102     Ella
103   Oliver

In [20]:
df2

       종목명
ID
100   삼성전자
100   LG전자
101    카카오
101  NAVER
101    현대차

In [21]:
# (1)
df = pd.merge(df1, df2, on='ID')
df

        Name    종목명
ID
100  Brayden   삼성전자
100  Brayden   LG전자
101    Clara    카카오
101    Clara  NAVER
101    Clara    현대차

In [22]:
# (2)
df = pd.merge(df1, df2, how='outer', on='ID')
df

        Name    종목명
ID
100  Brayden   삼성전자
100  Brayden   LG전자
101    Clara    카카오
101    Clara  NAVER
101    Clara    현대차
102     Ella    NaN
103   Oliver    NaN

In [23]:
# (3)
df2 = pd.DataFrame(data=data2, columns=['아이디','종목명'])
df2

   아이디    종목명
0  100   삼성전자
1  100   LG전자
2  101    카카오
3  101  NAVER
4  101    현대차

In [24]:
df = pd.merge(df1, df2, left_on='ID', right_on='아이디')
df

      Name  아이디    종목명
0  Brayden  100   삼성전자
1  Brayden  100   LG전자
2    Clara  101    카카오
3    Clara  101  NAVER
4    Clara  101    현대차

### [문제4]

In [25]:
data1 = {
    'ID' : [100, 101, 102, 103],
    'Name' : ['Brayden', 'Clara', 'Ella', 'Oliver']
}
data2 = [
    [100, '삼성전자'],
    [100, 'LG전자'],
    [101, '카카오'],
    [101, 'NAVER'],
    [101, '현대차']
]
df1 = pd.DataFrame(data1)
df1.set_index('ID', inplace=True)
df2 = pd.DataFrame(data=data2, columns=['ID','종목명'])
df2.set_index('ID', inplace=True)

In [26]:
df1

        Name
ID
100  Brayden
101    Clara
102     Ella
103   Oliver

In [27]:
df2

       종목명
ID
100   삼성전자
100   LG전자
101    카카오
101  NAVER
101    현대차

In [28]:
df = pd.merge(df1, df2, left_index=True, right_index=True)
df

        Name    종목명
ID
100  Brayden   삼성전자
100  Brayden   LG전자
101    Clara    카카오
101    Clara  NAVER
101    Clara    현대차