In [1]:
import pandas as pd
import numpy as np

## [문제1]

In [7]:
data = [
    ['KFC', 1000, 4.5],
    ['McDonald', 2000, 3.9],
    ['SchoolFood', 2500, 4.2]
]
col = ['food', 'price', 'rating']
row = [0, 1, 2]

df = pd.DataFrame(data, row, col)
df

         food  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

## [문제2]

In [8]:
df[['food', 'rating']]

         food  rating
0         KFC     4.5
1    McDonald     3.9
2  SchoolFood     4.2

## [문제3]

In [9]:
df = df.rename({'food' : 'place'}, axis=1)
df

        place  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2